source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCSegmentBarController' do
  pod "JCSegmentBarController", :path => "../"
end

target 'Tests' do
  pod "JCSegmentBarController", :path => "../"
end
