source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCSegmentBarController_Example' do
  pod "JCSegmentBarController", :path => "../"
end

target 'JCSegmentBarController_Tests' do
  pod "JCSegmentBarController", :path => "../"
end
